# a config file for flow matching model 
input_dim: 76
output_dim: 1
hidden_dim: 32
model_type: mlp
num_layers: 4
dropout_rate: 0.0
use_batch_norm: false
lr: 0.001
batch_size: 128
iterations: 10000
print_every: 50
device: null